hideui singleuser,hints,badges

icons_dir themes/rEFInd-dark-theme/icons

banner themes/rEFInd-dark-theme/background.png
banner_scale fillscreen

selection_big themes/rEFInd-dark-theme/selection_big.png
selection_small themes/rEFInd-dark-theme/selection_small.png